@echo off
diff test\fay.out          ..\out\fay.out                > test\fay.dif
diff test\align.out        ..\out\align.out              > test\align.dif
diff test\ancestor.out     ..\out\ancestor.out           > test\ancestor.dif
diff test\ancestor2.out    ..\out\ancestor2.out          > test\ancestor2.dif
diff test\backtracerr.out  ..\out\backtracerr.out        > test\backtracerr.dif
diff test\basic.out        ..\out\basic.out              > test\basic.dif
diff test\bench.out        ..\out\bench.out              > test\bench.dif
diff test\binrdwt.out      ..\out\binrdwt.out            > test\binrdwt.dif
REM diff test\case.out         ..\out\case.out               > test\case.dif
diff test\cfor.out         ..\out\cfor.out               > test\cfor.dif
diff test\clock.out        ..\out\clock.out              > test\clock.dif
diff test\cntchars.out     ..\out\cntchars.out           > test\cntchars.dif
diff test\cutter.out       ..\out\cutter.out             > test\cutter.dif
diff test\eightqueens.out  ..\out\eightqueens.out        > test\eightqueens.dif
diff test\expotst.out      ..\out\expotst.out            > test\expotst.dif
diff test\fay.out          ..\out\fay.out                > test\fay.dif
diff test\ffunc.out        ..\out\ffunc.out              > test\ffunc.dif
diff test\fnested.out      ..\out\fnested.out            > test\fnested.dif
diff test\form.out         ..\out\form.out               > test\form.dif
diff test\fproc.out        ..\out\fproc.out              > test\fproc.dif
diff test\funcs.out        ..\out\funcs.out              > test\funcs.dif
diff test\gencard.out      ..\out\gencard.out            > test\gencard.dif
diff test\gordon.out       ..\out\gordon.out             > test\gordon.dif
diff test\hamachi.out      ..\out\hamachi.out            > test\hamachi.dif
diff test\hanoi.out        ..\out\hanoi.out              > test\hanoi.dif
diff test\hugereal.out     ..\out\hugereal.out           > test\hugereal.dif
diff test\index.out        ..\out\index.out              > test\index.dif
diff test\insan.out        ..\out\insan.out              > test\insan.dif
diff test\math.out         ..\out\math.out               > test\math.dif
diff test\nmaze.out        ..\out\nmaze.out              > test\nmaze.dif
diff test\nonlocgoto.out   ..\out\nonlocgoto.out         > test\nonlocgoto.dif
diff test\numericio.out    ..\out\numericio.out          > test\numericio.dif
diff test\palindromes.out  ..\out\palindromes.out        > test\palindromes.dif
diff test\pcerror.out      ..\out\pcerror.out            > test\pcerror.dif
REM diff test\pcextn.out       ..\out\pcextn.out             > test\pcextn.dif
diff test\permute.out      ..\out\permute.out            > test\permute.dif
diff test\peter.out        ..\out\peter.out              > test\peter.dif
diff test\piextn.out       ..\out\piextn.out             > test\piextn.dif
diff test\powersoftwo.out  ..\out\powersoftwo.out        > test\powersoftwo.dif
diff test\pretty.out       ..\out\pretty.out             > test\pretty.dif
diff test\primes.out       ..\out\primes.out             > test\primes.dif
diff test\procs.out        ..\out\procs.out              > test\procs.dif
diff test\pvs1.out         ..\out\pvs1.out               > test\pvs1.dif
diff test\pvs2.out         ..\out\pvs2.out               > test\pvs2.dif
diff test\pvs3.out         ..\out\pvs3.out               > test\pvs3.dif
diff test\quicksort.out    ..\out\quicksort.out          > test\quicksort.dif
diff test\random.out       ..\out\random.out             > test\random.dif
diff test\rdpal.out        ..\out\rdpal.out              > test\rdpal.dif
diff test\rdwt.out         ..\out\rdwt.out               > test\rdwt.dif
diff test\real.out         ..\out\real.out               > test\real.dif
diff test\realout.out      ..\out\realout.out            > test\realout.dif
diff test\reset.out        ..\out\reset.out              > test\reset.dif
diff test\scaltst.out      ..\out\scaltst.out            > test\scaltst.dif
diff test\sequin.out       ..\out\sequin.out             > test\sequin.dif
diff test\setest.out       ..\out\setest.out             > test\setest.dif
diff test\setret.out       ..\out\setret.out             > test\setret.dif
diff test\shoemake.out     ..\out\shoemake.out           > test\shoemake.dif
diff test\size.out         ..\out\size.out               > test\size.dif
diff test\sort.out         ..\out\sort.out               > test\sort.dif
diff test\strngs.out       ..\out\strngs.out             > test\strngs.dif
diff test\t01.out          ..\out\t01.out                > test\t01.dif
diff test\t03.out          ..\out\t03.out                > test\t03.dif
diff test\t04.out          ..\out\t04.out                > test\t04.dif
diff test\t05.out          ..\out\t05.out                > test\t05.dif
diff test\t06.out          ..\out\t06.out                > test\t06.dif
diff test\t07.out          ..\out\t07.out                > test\t07.dif
diff test\t08.out          ..\out\t08.out                > test\t08.dif
diff test\t09.out          ..\out\t09.out                > test\t09.dif
diff test\t10.out          ..\out\t10.out                > test\t10.dif
diff test\t11.out          ..\out\t11.out                > test\t11.dif
diff test\t12.out          ..\out\t12.out                > test\t12.dif
diff test\t13.out          ..\out\t13.out                > test\t13.dif
diff test\t14.out          ..\out\t14.out                > test\t14.dif
diff test\t15.out          ..\out\t15.out                > test\t15.dif
diff test\t16.out          ..\out\t16.out                > test\t16.dif
diff test\t17.out          ..\out\t17.out                > test\t17.dif
diff test\t18.out          ..\out\t18.out                > test\t18.dif
diff test\t19.out          ..\out\t19.out                > test\t19.dif
diff test\t20.out          ..\out\t20.out                > test\t20.dif
diff test\t21.out          ..\out\t21.out                > test\t21.dif
diff test\testeoln.out     ..\out\testeoln.out           > test\testeoln.dif
diff test\testio.out       ..\out\testio.out             > test\testio.dif
diff test\transpose.out    ..\out\transpose.out          > test\transpose.dif
diff test\wnj.out          ..\out\wnj.out                > test\wnj.dif
:done
