@echo off
diff test\fay.out          ..\tstpx\out\fay.out                > test\fay.dif
diff test\align.out        ..\tstpx\out\align.out              > test\align.dif
diff test\ancestor.out     ..\tstpx\out\ancestor.out           > test\ancestor.dif
diff test\backtrac.out     ..\tstpx\out\backtrac.out           > test\backtrac.dif
diff test\basic.out        ..\tstpx\out\basic.out              > test\basic.dif
diff test\bench.out        ..\tstpx\out\bench.out              > test\bench.dif
diff test\binrdwt.out      ..\tstpx\out\binrdwt.out            > test\binrdwt.dif
diff test\case.out         ..\tstpx\out\case.out               > test\case.dif
diff test\cfor.out         ..\tstpx\out\cfor.out               > test\cfor.dif
diff test\clock.out        ..\tstpx\out\clock.out              > test\clock.dif
diff test\cntchars.out     ..\tstpx\out\cntchars.out           > test\cntchars.dif
diff test\cutter.out       ..\tstpx\out\cutter.out             > test\cutter.dif
diff test\eightque.out     ..\tstpx\out\eightque.out           > test\eightque.dif
diff test\expotst.out      ..\tstpx\out\expotst.out            > test\expotst.dif
diff test\fay.out          ..\tstpx\out\fay.out                > test\fay.dif
diff test\ffunc.out        ..\tstpx\out\ffunc.out              > test\ffunc.dif
diff test\fnested.out      ..\tstpx\out\fnested.out            > test\fnested.dif
diff test\form.out         ..\tstpx\out\form.out               > test\form.dif
diff test\fproc.out        ..\tstpx\out\fproc.out              > test\fproc.dif
diff test\funcs.out        ..\tstpx\out\funcs.out              > test\funcs.dif
diff test\gencard.out      ..\tstpx\out\gencard.out            > test\gencard.dif
diff test\gordon.out       ..\tstpx\out\gordon.out             > test\gordon.dif
diff test\hamachi.out      ..\tstpx\out\hamachi.out            > test\hamachi.dif
diff test\hanoi.out        ..\tstpx\out\hanoi.out              > test\hanoi.dif
diff test\hugereal.out     ..\tstpx\out\hugereal.out           > test\hugereal.dif
diff test\index.out        ..\tstpx\out\index.out              > test\index.dif
diff test\insan.out        ..\tstpx\out\insan.out              > test\insan.dif
diff test\math.out         ..\tstpx\out\math.out               > test\math.dif
diff test\nmaze.out        ..\tstpx\out\nmaze.out              > test\nmaze.dif
diff test\nonlocgo.out     ..\tstpx\out\nonlocgo.out           > test\nonlocgo.dif
diff test\numerici.out     ..\tstpx\out\numerici.out           > test\numerici.dif
diff test\palindro.out     ..\tstpx\out\palindro.out           > test\palindro.dif
diff test\pcerror.out      ..\tstpx\out\pcerror.out            > test\pcerror.dif
diff test\pcextn.out       ..\tstpx\out\pcextn.out             > test\pcextn.dif
diff test\permute.out      ..\tstpx\out\permute.out            > test\permute.dif
diff test\peter.out        ..\tstpx\out\peter.out              > test\peter.dif
diff test\pxextn.out       ..\tstpx\out\pxextn.out             > test\pxextn.dif
diff test\powersof.out     ..\tstpx\out\powersof.out           > test\powersof.dif
diff test\pretty.out       ..\tstpx\out\pretty.out             > test\pretty.dif
diff test\primes.out       ..\tstpx\out\primes.out             > test\primes.dif
diff test\procs.out        ..\tstpx\out\procs.out              > test\procs.dif
diff test\pvs1.out         ..\tstpx\out\pvs1.out               > test\pvs1.dif
diff test\pvs2.out         ..\tstpx\out\pvs2.out               > test\pvs2.dif
diff test\pvs3.out         ..\tstpx\out\pvs3.out               > test\pvs3.dif
diff test\quicksor.out     ..\tstpx\out\quicksor.out           > test\quicksor.dif
diff test\random.out       ..\tstpx\out\random.out             > test\random.dif
diff test\rdpal.out        ..\tstpx\out\rdpal.out              > test\rdpal.dif
diff test\rdwt.out         ..\tstpx\out\rdwt.out               > test\rdwt.dif
diff test\real.out         ..\tstpx\out\real.out               > test\real.dif
diff test\realout.out      ..\tstpx\out\realout.out            > test\realout.dif
diff test\reset.out        ..\tstpx\out\reset.out              > test\reset.dif
diff test\scaltst.out      ..\tstpx\out\scaltst.out            > test\scaltst.dif
diff test\sequin.out       ..\tstpx\out\sequin.out             > test\sequin.dif
diff test\setest.out       ..\tstpx\out\setest.out             > test\setest.dif
diff test\setret.out       ..\tstpx\out\setret.out             > test\setret.dif
diff test\shoemake.out     ..\tstpx\out\shoemake.out           > test\shoemake.dif
diff test\size.out         ..\tstpx\out\size.out               > test\size.dif
diff test\sort.out         ..\tstpx\out\sort.out               > test\sort.dif
diff test\strngs.out       ..\tstpx\out\strngs.out             > test\strngs.dif
diff test\t01.out          ..\tstpx\out\t01.out                > test\t01.dif
diff test\t03.out          ..\tstpx\out\t03.out                > test\t03.dif
diff test\t04.out          ..\tstpx\out\t04.out                > test\t04.dif
diff test\t05.out          ..\tstpx\out\t05.out                > test\t05.dif
diff test\t06.out          ..\tstpx\out\t06.out                > test\t06.dif
diff test\t07.out          ..\tstpx\out\t07.out                > test\t07.dif
diff test\t08.out          ..\tstpx\out\t08.out                > test\t08.dif
diff test\t09.out          ..\tstpx\out\t09.out                > test\t09.dif
diff test\t10.out          ..\tstpx\out\t10.out                > test\t10.dif
diff test\t11.out          ..\tstpx\out\t11.out                > test\t11.dif
diff test\t12.out          ..\tstpx\out\t12.out                > test\t12.dif
diff test\t13.out          ..\tstpx\out\t13.out                > test\t13.dif
diff test\t14.out          ..\tstpx\out\t14.out                > test\t14.dif
diff test\t15.out          ..\tstpx\out\t15.out                > test\t15.dif
diff test\t16.out          ..\tstpx\out\t16.out                > test\t16.dif
diff test\t17.out          ..\tstpx\out\t17.out                > test\t17.dif
diff test\t18.out          ..\tstpx\out\t18.out                > test\t18.dif
diff test\t19.out          ..\tstpx\out\t19.out                > test\t19.dif
diff test\t20.out          ..\tstpx\out\t20.out                > test\t20.dif
diff test\t21.out          ..\tstpx\out\t21.out                > test\t21.dif
diff test\testeoln.out     ..\tstpx\out\testeoln.out           > test\testeoln.dif
diff test\testio.out       ..\tstpx\out\testio.out             > test\testio.dif
diff test\transpos.out     ..\tstpx\out\transpos.out           > test\transpos.dif
diff test\wnj.out          ..\tstpx\out\wnj.out                > test\wnj.dif
:done
